# fly.toml app configuration file generated for next-ecomm-rygobackend on 2023-06-20T10:27:17+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "next-ecomm-rygobackend"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
